stages:
  prepare_split:
    cmd: python -m src.data.prepare_split
    deps:
      - src/data/prepare_split.py
    outs:
      - data/cifar_split.npz
    params:
      - seed
      - split.train_percent
      - split.test_percent

  train_baseline:
    cmd: python -m experiments.train_baseline
    deps:
      - experiments/train_baseline.py
      - data/cifar_split.npz
    outs:
      - checkpoints/baseline_model.pt
    params:
      - baseline.train.epochs
      - baseline.train.learning_rate
      - model.num_classes
      - model.latent_channels
      - model.pretrained

  pretrain_ae:
    cmd: python -m pretrain.ae_pretrain
    deps:
      - pretrain/ae_pretrain.py
      - src/models/ae.py
      - data/cifar_split.npz
    outs:
      - checkpoints/ae_pretrained.pth
    params:
      - ae.pretrain.epochs
      - ae.pretrain.learning_rate
      - ae.recon_loss_weight
      - ae.freeze
      - model.latent_channels

  train_ae:
    cmd: python -m experiments.train_ae_on_pooling
    deps:
      - experiments/train_ae_on_pooling.py
      - src/models/ae.py
      - checkpoints/ae_pretrained.pth
      - data/cifar_split.npz
    outs:
      - checkpoints/ae_model.pt
    params:
      - ae.train.epochs
      - ae.train.learning_rate
      - ae.recon_loss_weight
      - ae.freeze
      - ae.train.cls_loss_weight
      - model.latent_channels
      - model.num_classes

  pretrain_vae:
    cmd: python -m pretrain.vae_pretrain
    deps:
      - pretrain/vae_pretrain.py
      - src/models/vae.py
      - data/cifar_split.npz
    outs:
      - checkpoints/vae_pretrained.pth
    params:
      - vae.pretrain.epochs
      - vae.pretrain.learning_rate
      - vae.hidden_ch
      - vae.latent_ch
      - vae.beta

  train_vae:
    cmd: python -m experiments.train_vae_on_pooling
    deps:
      - experiments/train_vae_on_pooling.py
      - src/models/vae.py
      - checkpoints/vae_pretrained.pth
      - data/cifar_split.npz
    outs:
      - checkpoints/vae_model.pt
    params:
      - vae.train.epochs
      - vae.train.learning_rate
      - vae.train.weight_decay
      - vae.train.cls_loss_weight
      - vae.hidden_ch
      - vae.latent_ch
      - vae.beta

  evaluate:
    foreach:
      - baseline
      - ae
      - vae
#      - vae_pretrained
      # - simclr
      # - byol
    do:
      cmd: python -m experiments.evaluate --model_type ${item}
      deps:
        - experiments/evaluate.py
        - checkpoints/${item}_model.pt
        - data/cifar_split.npz
      outs:
        - results/${item}_acc.json
      params:
        - model.latent_channels
        - model.num_classes
