seed: 50

split:
  train_percent: 1      # % of CIFAR-10 train set to use
  test_percent: 0.1    # % of CIFAR-10 test set to use

model:
  latent_channels: 128
  num_classes: 10
  pretrained: true      # ImageNet weights for ResNet trunk

baseline:
  train:
    epochs: 1
    learning_rate: 0.001

ae:
  recon_loss_weight: 0.5
  pretrain:
    epochs: 1
    learning_rate: 0.001
  train:
    epochs: 1
    batch_size: 32
    learning_rate: 0.001
    cls_loss_weight: 1.0

vae:
  beta: 10.0
  hidden_ch: 256
  latent_ch: 128
  pretrain:
    epochs: 1
    learning_rate: 0.0001
  train:
    epochs: 1
    batch_size: 64
    cls_loss_weight: 5
    learning_rate: 0.0001
    weight_decay: 0.000001

# Placeholders for future SSL encoders
simclr:
  projection_dim: 128
  temperature: 0.5
  train:
    epochs: 1
    batch_size: 256
    learning_rate: 0.001

byol:
  projection_dim: 128
  train:
    epochs: 1
    batch_size: 256
    learning_rate: 0.001

paths:
  data_dir: "data"
  results_dir: "results"
  checkpoints_dir: "checkpoints"
